CREATE TABLE IF NOT EXISTS auditoria_operaciones (
    id_auditoria BIGINT NOT NULL AUTO_INCREMENT,
    fecha_hora DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    id_usuario INT NULL,
    correo_usuario VARCHAR(120) NOT NULL,
    nombre_usuario VARCHAR(170) NOT NULL,
    rol_usuario VARCHAR(40) NOT NULL,
    modulo VARCHAR(50) NOT NULL,
    accion VARCHAR(70) NOT NULL,
    metodo_http VARCHAR(10) NOT NULL,
    ruta VARCHAR(255) NOT NULL,
    recurso_id VARCHAR(80) NULL,
    resultado VARCHAR(20) NOT NULL,
    estado_http SMALLINT NOT NULL,
    duracion_ms BIGINT NOT NULL DEFAULT 0,
    direccion_ip VARCHAR(64) NULL,
    request_id VARCHAR(64) NULL,
    detalle VARCHAR(500) NULL,
    tipo_error VARCHAR(120) NULL,
    PRIMARY KEY (id_auditoria),
    INDEX idx_auditoria_fecha (fecha_hora),
    INDEX idx_auditoria_usuario_fecha (id_usuario, fecha_hora),
    INDEX idx_auditoria_modulo_fecha (modulo, fecha_hora),
    INDEX idx_auditoria_resultado_fecha (resultado, fecha_hora),
    INDEX idx_auditoria_accion_fecha (accion, fecha_hora)
) ENGINE=InnoDB;
